# Generated by Django 3.0.6 on 2020-06-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200625_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivecoins3daysoffer',
            name='gained_offer',
        ),
    ]
